### ISSUE TITLE
Bot performance

### ISSUE THREAD

**Issue by javico-dev11** [nikita-doronin/crypto_hedge_scalping_bot#1]
Hello, how are you?
I've been checking out your bot and I see that it's an interesting strategy, congratulations.
Are you using it? How have you been doing with the results?

**Comment by nikita-doronin** [comment]
Hi there 🙋‍♂️
Thanks for asking! Not really this strategy, but modification of it.
It is still under development and under first phase of testing. A huge job needs to be done before rollout. However, I have some real trading results of it:

![image](https://github.com/user-attachments/assets/a0b0c9df-ac9f-41cd-ab6a-e1e30d4bbc90)

**Comment by javico-dev11** [comment]
Thanks for your reply, I hope your tests go well, I'll be waiting for more news. 
Regards
